spring:
  jackson:
    time-zone: Asia/Phnom_Penh
  datasource:
    url: jdbc:postgresql://localhost:5169/share_db
    username: thongfazon
    password: itp@168
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}